"use client";
import { FormEvent, useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BriefcaseBusiness, CircleUserRound, Cloud, Code2, Database, Download, ExternalLink, GitFork, GraduationCap, Layers3, Mail, Menu, Rocket, Send, X } from "lucide-react";
import { profile, experience, education, skills, skillLogos } from "../data/profile";
import { projects } from "../data/projects";
import { certifications } from "../data/certifications";

const nav=["Home","About","Experience","Projects","Skills","Education","Certifications","Contact"];
const tech=["Next.js","React","FastAPI","Python","Docker","PostgreSQL","TypeScript"];
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.45}};

function Logo(){return <a className="mdg-logo" href="#home" aria-label="Mohamed Dhia Gaied home"><span><b>M</b>D<i>G</i></span><small>MOHAMED DHIA<br/>GAIED</small></a>}
function Navbar(){const[open,setOpen]=useState(false);return <motion.header className="topbar" initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} transition={{duration:.45}}><nav className="wide"><Logo/><div className={`nav-items ${open?"is-open":""}`}>{nav.map(n=><a key={n} href={`#${n.toLowerCase()}`} onClick={()=>setOpen(false)}>{n}</a>)}{profile.cvAvailable&&<div className="mobile-cv-links"><a href={profile.cv} download="Mohamed-Dhia-Gaied-CV.pdf"><Download/> Download CV</a><a href={profile.cv} target="_blank" rel="noopener noreferrer"><ExternalLink/> View CV</a></div>}</div><div className="nav-ctas">{profile.cvAvailable&&<a className="cv-button" href={profile.cv} download="Mohamed-Dhia-Gaied-CV.pdf"><Download/> Download CV</a>}<button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></nav></motion.header>}
function Hero(){const reduce=useReducedMotion();return <section id="home" className="hero wide"><motion.div className="hero-text" initial={{opacity:0,x:-25}} animate={{opacity:1,x:0}} transition={{duration:.55}}><p className="hello">● Hello, I’m 👋</p><h1>MOHAMED<br/>DHIA <em>GAIED</em></h1><h2>Software Engineering Developer<br/>& <span>Computer Engineering Student</span></h2><p>I build scalable web applications with a strong focus on clean code, backend APIs, databases, and thoughtful user experiences. Currently expanding my skills in <b>Cloud Computing.</b></p><div className="mini-tags"><span>Full-Stack Development</span><span>Backend APIs</span><span>Cloud Learning</span><span>Problem Solver</span></div><div className="hero-actions"><a className="btn primary" href="#projects">View Projects <ArrowRight/></a>{profile.cvAvailable&&<><a className="btn" href={profile.cv} download="Mohamed-Dhia-Gaied-CV.pdf"><Download/> Download CV</a><a className="btn" href={profile.cv} target="_blank" rel="noopener noreferrer"><ExternalLink/> View CV</a></>}<a className="btn" href="#contact">Contact Me <Mail/></a></div><div className="socials"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><CircleUserRound/></a>{profile.githubUrl&&<a href={profile.githubUrl} target="_blank" rel="noopener noreferrer" aria-label="GitHub"><GitFork/></a>}<a href={`mailto:${profile.email}`} aria-label="Email"><Mail/></a></div></motion.div><motion.div className="hero-visual" initial={{opacity:0,scale:.95,y:16}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.6}}><div className="circuit c1"/><div className="circuit c2"/><div className="neon-ring"><div className="portrait-crop"><img src="/portrait-reference.png" alt="Mohamed Dhia Gaied portrait from the supplied reference"/></div></div><div className="tech-stack">{tech.map((t,i)=><motion.span key={t} animate={reduce?{}:{y:[0,-4,0]}} transition={{duration:3+i*.22,repeat:Infinity}}>{t}</motion.span>)}</div><motion.div className="learning" animate={reduce?{}:{y:[0,-5,0]}} transition={{duration:3.4,repeat:Infinity}}><Cloud/><small>Currently Learning</small><strong>Cloud Computing</strong><i/></motion.div></motion.div></section>}
function Stats(){const values=[{icon:BriefcaseBusiness,n:experience.length+"+",label:"Experiences / Internships"},{icon:Code2,n:projects.length+"+",label:"Verified Projects"},{icon:GraduationCap,n:certifications.length+"+",label:"Certifications Earned"},{icon:Layers3,n:Object.values(skills).flat().length+"+",label:"Technologies"},{icon:Cloud,n:"1",label:"Current Focus"}];return <motion.section className="stats-strip wide" {...reveal}>{values.map(v=><div key={v.label}><v.icon/><strong>{v.n}</strong><span>{v.label}</span></div>)}</motion.section>}
const what=[{icon:Code2,title:"Web Application Development"},{icon:Cloud,title:"Cloud Computing (Learning)"},{icon:Rocket,title:"RESTful API Development"},{icon:Layers3,title:"Clean Code & Best Practices"},{icon:Database,title:"Database Design & Management"},{icon:Code2,title:"Problem Solving & Debugging"}];
function About(){return <section id="about" className="section wide dual"><motion.article className="panel" {...reveal}><h3>About Me</h3><p>I’m a Software Engineering Developer and Computer Engineering student passionate about building robust, scalable applications. I enjoy solving complex problems and developing efficient solutions across frontend, backend, databases, and software architecture.</p><p>I’m currently expanding my skills in Cloud Computing and modern application architectures.</p><div className="chip-row">{["Full-Stack Development","Backend APIs","Database Design","Software Architecture","Problem Solving","Team Collaboration"].map(x=><span key={x}>{x}</span>)}</div></motion.article></section>}
function Experience(){return <motion.section id="experience" className="section wide panel" {...reveal}><div className="panel-title"><h3>Experience / Internships</h3></div><div className="experience-line">{experience.map((e,i)=><motion.article key={e.company} whileHover={{y:-3}} transition={{duration:.2}}><i/><time>{e.date}</time><h4>{e.company}</h4><b>{e.role}</b><p>{e.description}</p></motion.article>)}</div></motion.section>}
function Projects(){return <motion.section id="projects" className="section wide panel" {...reveal}><div className="panel-title"><h3>Featured Projects</h3><a href="/projects">View All Projects <ArrowRight/></a></div><div className="project-grid">{projects.filter(p=>p.featured).map(p=><motion.article key={p.slug} whileHover={{y:-4}}><div className="project-art" role="img" aria-label={`${p.title} interface preview`} style={{backgroundImage:`url(${p.image})`,backgroundPosition:p.imagePosition}}/><h4>{p.title}</h4><p>{p.description}</p><div className="chip-row">{p.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><a href={`/projects/${p.slug}`}>Case Study <ArrowRight/></a>{p.githubUrl&&<a className="github-action" href={p.githubUrl} target="_blank" rel="noopener noreferrer"><GitFork/><span>GitHub</span><ExternalLink/></a>}{p.demoUrl&&<a href={p.demoUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/> Live Demo</a>}</div></motion.article>)}</div></motion.section>}
function Knowledge(){return <section className="section wide lower-grid"><motion.article id="skills" className="panel skills" {...reveal}><div className="panel-title"><h3>Technical Skills</h3></div><div className="skills-grid">{Object.entries(skills).map(([group,list])=><div key={group}><h4>{group}</h4>{list.map(s=>{const icon=skillLogos[s];return <p className="skill-item" key={s}>{icon&&<img src={`/logos/skills/${icon}.svg`} alt=""/>}<span>{s.trim()}</span></p>})}</div>)}</div></motion.article><motion.article id="certifications" className="panel" {...reveal}><div className="panel-title"><h3>Certifications</h3></div><div className="cert-grid">{certifications.map(c=><div key={c.name}><span className="cert-logo"><img src={c.logo} alt={`${c.issuer} logo`}/></span><p><b>{c.name}</b><small>{c.issuer} · {c.date}</small>{"credentialUrl" in c&&c.credentialUrl&&<a href={c.credentialUrl} target="_blank" rel="noopener noreferrer">View Credential <ExternalLink/></a>}</p></div>)}</div></motion.article><motion.article id="education" className="panel education" {...reveal}><div className="panel-title"><h3>Education</h3></div>{education.map(e=><div key={e.date}><i/><time>{e.date}</time><b>{e.degree}</b><span>{e.field}</span><small>{e.school}</small></div>)}</motion.article></section>}
function Contact(){const[state,setState]=useState<"idle"|"sending"|"success"|"error">("idle");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");const form=new FormData(e.currentTarget);const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});setState(response.ok?"success":"error");if(response.ok)e.currentTarget.reset()}return <motion.section id="contact" className="section wide contact panel" {...reveal}><div><div className="rocket"><Rocket/></div><h2>Let’s build something amazing together! 🚀</h2><p>I’m open to discussing opportunities, collaborations, and exciting software projects.</p><div className="contact-links"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><CircleUserRound/> LinkedIn</a><a href={`mailto:${profile.email}`}><Mail/> {profile.email}</a>{profile.githubUrl&&<a href={profile.githubUrl} target="_blank" rel="noopener noreferrer"><GitFork/> GitHub</a>}</div></div><form onSubmit={submit}><input name="website" className="honeypot" tabIndex={-1} autoComplete="off"/><div><label>Name<input required maxLength={80} name="name"/></label><label>Email<input required maxLength={160} type="email" name="email"/></label></div><label>Subject<input required maxLength={140} name="subject"/></label><label>Message<textarea required minLength={10} maxLength={3000} name="message" rows={4}/></label><button className="btn primary" disabled={state==="sending"}>{state==="sending"?"Sending...":"Send Message"}<Send/></button>{state==="success"&&<p className="toast success">Message sent successfully!</p>}{state==="error"&&<p className="toast error">Unable to send message. Please try again.</p>}</form></motion.section>}
function Footer(){return <motion.footer className="footer wide" {...reveal}><Logo/><p>© {new Date().getFullYear()} Mohamed Dhia Gaied. All rights reserved.</p><div className="socials"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><CircleUserRound/></a><a href={`mailto:${profile.email}`} aria-label="Email"><Mail/></a><a href="#home" aria-label="Back to top">↑</a></div></motion.footer>}
export function Portfolio(){useEffect(()=>{const move=(e:MouseEvent)=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")};addEventListener("mousemove",move);return()=>removeEventListener("mousemove",move)},[]);return <><a className="skip" href="#home">Skip to content</a><div className="cursor-glow"/><Navbar/><main><Hero/><Stats/><About/><Experience/><Projects/><Knowledge/><Contact/></main><Footer/></>}
